services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./storage:/img-compress/storage
      - ./logs:/img-compress/logs
      - ./assets:/img-compress/assets
    ports:
      - "8087:8080"